sonar.projectKey=khanhcr123456_Pet_Care_FE
sonar.organization=khanhcr123456

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Pet_Care_FE
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.test.*, dist/**, build/**, .vite/**

# Frontend parameters
sonar.sourceEncoding=UTF-8
